### PR TITLE
Optimism givpower

### PR DESCRIPTION
**Pull request by divine-comedian**
Modifying the GIVpower distributor contract to work on Optimism where there is no Gardens or TokenManagerHook. 

This is the GardensUnipoolDistributor contract that's been modified to more closely match the basic UnipoolDistributor contract.
https://github.com/Giveth/givpower/pull/32/files#diff-e92b8746b42c56ee4803dbacf9339cd14f2a7bc0cf1168fd52174b5154aafda7

ref https://github.com/Giveth/giveth-dapps-v2/issues/2497

### CODE REVIEW

**Comment by laurenluz** [comment]
We discussed in the GIVeconomy call that we should have Sem audit these changes before we push it forward. if we're modifying staking contracts, we should make sure we have some experienced eyes on it. @aminlatifi @divine-comedian

**Comment by divine-comedian** [comment]
@aminlatifi I merged your review PR, next steps is merge or should we get a look from @sembrestels ?

**Comment by aminlatifi** [comment]
> @aminlatifi I merged your review PR, next steps is merge or should we get a look from @sembrestels ?

Yes, it would be great.
@laurenluz

**Comment by divine-comedian** [comment]
# Notes from Sem's First Review

missing the `earned` function from the GardenUnipool 

the `claimableStream` from the GardenUnipool was renamed to `earned`in UnipoolTokenDistro but there is no function in the new contract doing what `earned` did in the GardenUnipool

match closer the UnipoolTokenDistro variable names to the GardenUnipoolDistro variable names unless there is a specific reason.  `getBlockTimeStamp`

rename `_uni` to `_depositToken`

there is inside of the UnipoolTokenDistributor we are storing the `_balances` (private) and also storing the same balances in UnipoolGIVpower as `uniBalances` (public)

The `_balances` could be changed to internal to allow it to be called by the Unipool TokenDistro or simply just define one public mapping to be managed and viewable by both contracts 

the fallback function doesn't have any comments as to the logic of why it is written that way, what is the purpose of the `if`statement and `exit` function call.

**Comment by laurenluz** [comment]
@aminlatifi can you have a look at these notes and fix up the contract?

**Comment by aminlatifi** [comment]
> # Notes from Sem's First Review
> missing the `earned` function from the GardenUnipool
> 
> the `claimableStream` from the GardenUnipool was renamed to `earned`in UnipoolTokenDistro but there is no function in the new contract doing what `earned` did in the GardenUnipool
> 
> match closer the UnipoolTokenDistro variable names to the GardenUnipoolDistro variable names unless there is a specific reason. `getBlockTimeStamp`
> 
> rename `_uni` to `_depositToken`
> 
> there is inside of the UnipoolTokenDistributor we are storing the `_balances` (private) and also storing the same balances in UnipoolGIVpower as `uniBalances` (public)
> 
> The `_balances` could be changed to internal to allow it to be called by the Unipool TokenDistro or simply just define one public mapping to be managed and viewable by both contracts
> 
> the fallback function doesn't have any comments as to the logic of why it is written that way, what is the purpose of the `if`statement and `exit` function call.


Thanks @sembrestels for reviewing.

We don't need the `claimableStream`method here. In fact, GardenUnipool is the result of modifications to the standard unipool. One of the changes was renaming `earned` function to `claimableStream` because 1Hive garden UI shows `earned` function return value to the user and the user expects to receive that value on claim! So we wrote `earned` function in a way which return the liquid part of reward

Replaced `_getBlockTimeStamp` with `getTimestamp`

Renamed uni to depositToken

The `_balances` represents users power balance (deposited token amount + reward by locking), on the other hand `uniBalances` (I renamed it to `depositTokenBalance`) holds amount of real liquidity deposited. These two are different and necessary for functionality.

@sembrestels I didn't get the point regarding the fallback function! can explain more?

**Comment by aminlatifi** [comment]
@sembrestels @divine-comedian Please see my changes at #34

**Pull request merged**
